import { Routes } from '@angular/router';
import { authGuard, inicioGuard, selecionarUnidadeGuard, telaGuard } from './core/auth.guard';
import { pendingChangesGuard } from './core/pending-changes.guard';

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./pages/login/login').then((m) => m.Login),
    title: 'Entrar',
  },
  {
    path: 'selecionar-unidade',
    loadComponent: () =>
      import('./pages/selecionar-unidade/selecionar-unidade').then((m) => m.SelecionarUnidade),
    canActivate: [selecionarUnidadeGuard],
    title: 'Selecione a unidade',
  },
  {
    path: '',
    loadComponent: () => import('./pages/shell/shell').then((m) => m.Shell),
    canActivate: [authGuard],
    children: [
      {
        path: 'dashboards/geral',
        loadComponent: () => import('./pages/dashboards/geral/geral').then((m) => m.DashboardGeral),
        canActivate: [telaGuard('DASHBOARD_GERAL')],
        title: 'Dashboard · Visão geral',
      },
      {
        path: 'dashboards/agendamentos',
        loadComponent: () =>
          import('./pages/dashboards/agendamentos/agendamentos').then((m) => m.DashboardAgendamentos),
        canActivate: [telaGuard('DASHBOARD_AGENDAMENTOS')],
        title: 'Dashboard · Agendamentos',
      },
      {
        path: 'dashboards/chats',
        loadComponent: () => import('./pages/dashboards/chats/chats').then((m) => m.DashboardChats),
        canActivate: [telaGuard('DASHBOARD_CHATS')],
        title: 'Dashboard · Chats ao vivo',
      },
      {
        path: 'dashboards/sau',
        loadComponent: () => import('./pages/dashboards/sau/sau').then((m) => m.DashboardSau),
        canActivate: [telaGuard('DASHBOARD_SAU')],
        title: 'Dashboard · SAU',
      },
      {
        path: 'dashboards/nps',
        loadComponent: () => import('./pages/dashboards/nps/nps').then((m) => m.DashboardNps),
        canActivate: [telaGuard('DASHBOARD_NPS')],
        title: 'Dashboard · NPS',
      },
      { path: 'inicio', canActivate: [inicioGuard], children: [] },
      {
        path: 'sem-permissao',
        loadComponent: () => import('./pages/sem-permissao/sem-permissao').then((m) => m.SemPermissao),
        title: 'Sem permissão',
      },
      {
        path: 'usuarios',
        loadComponent: () => import('./pages/usuarios/usuarios-list').then((m) => m.UsuariosList),
        canActivate: [telaGuard('USUARIOS')],
        title: 'Usuários',
      },
      {
        path: 'usuarios/novo',
        loadComponent: () => import('./pages/usuarios/usuario-form').then((m) => m.UsuarioForm),
        canActivate: [telaGuard('USUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo usuário',
      },
      {
        path: 'usuarios/:id',
        loadComponent: () => import('./pages/usuarios/usuario-form').then((m) => m.UsuarioForm),
        canActivate: [telaGuard('USUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar usuário',
      },
      {
        path: 'unidades',
        loadComponent: () => import('./pages/unidades/unidades-list').then((m) => m.UnidadesList),
        canActivate: [telaGuard('UNIDADES')],
        title: 'Unidades de Saúde',
      },
      {
        path: 'unidades/novo',
        loadComponent: () => import('./pages/unidades/unidade-form').then((m) => m.UnidadeForm),
        canActivate: [telaGuard('UNIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova unidade',
      },
      {
        path: 'unidades/:id',
        loadComponent: () => import('./pages/unidades/unidade-form').then((m) => m.UnidadeForm),
        canActivate: [telaGuard('UNIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar unidade',
      },
      {
        path: 'agendamentos',
        loadComponent: () => import('./pages/agendamentos/agendamentos-list').then((m) => m.AgendamentosList),
        canActivate: [telaGuard('AGENDAMENTOS')],
        title: 'Agendamentos',
      },
      {
        path: 'agendamentos/novo',
        loadComponent: () => import('./pages/agendamentos/agendamento-form').then((m) => m.AgendamentoForm),
        canActivate: [telaGuard('AGENDAMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo agendamento',
      },
      {
        path: 'agendamentos/:id',
        loadComponent: () => import('./pages/agendamentos/agendamento-form').then((m) => m.AgendamentoForm),
        canActivate: [telaGuard('AGENDAMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar agendamento',
      },
      {
        path: 'chats',
        loadComponent: () => import('./pages/chats/chats-list').then((m) => m.ChatsList),
        canActivate: [telaGuard('CHATS')],
        title: 'Chats ao vivo',
      },
      {
        path: 'chats/nova',
        loadComponent: () => import('./pages/chats/chat-nova').then((m) => m.ChatNova),
        canActivate: [telaGuard('CHATS')],
        title: 'Nova conversa',
      },
      {
        path: 'chats/:id',
        loadComponent: () => import('./pages/chats/chat-conversa').then((m) => m.ChatConversa),
        canActivate: [telaGuard('CHATS')],
        title: 'Conversa',
      },
      {
        path: 'sau',
        loadComponent: () => import('./pages/sau/sau-list').then((m) => m.SauList),
        canActivate: [telaGuard('SAU')],
        title: 'SAU',
      },
      {
        path: 'sau/:id',
        loadComponent: () => import('./pages/sau/sau-detalhe').then((m) => m.SauDetalhe),
        canActivate: [telaGuard('SAU')],
        title: 'Manifestação',
      },
      {
        path: 'tipos-manifestacao',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipos-manifestacao-list').then((m) => m.TiposManifestacaoList),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        title: 'Tipos de Manifestação',
      },
      {
        path: 'tipos-manifestacao/novo',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipo-manifestacao-form').then((m) => m.TipoManifestacaoForm),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo tipo de manifestação',
      },
      {
        path: 'tipos-manifestacao/:id',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipo-manifestacao-form').then((m) => m.TipoManifestacaoForm),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar tipo de manifestação',
      },
      {
        path: 'nps',
        loadComponent: () => import('./pages/nps/nps-list').then((m) => m.NpsList),
        canActivate: [telaGuard('NPS')],
        title: 'NPS',
      },
      {
        path: 'nps/:id',
        loadComponent: () => import('./pages/nps/nps-detalhe').then((m) => m.NpsDetalheComponent),
        canActivate: [telaGuard('NPS')],
        title: 'Avaliação',
      },
      {
        path: 'categorias-nps',
        loadComponent: () => import('./pages/categorias-nps/categorias-nps-list').then((m) => m.CategoriasNpsList),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        title: 'Categorias de NPS',
      },
      {
        path: 'categorias-nps/novo',
        loadComponent: () => import('./pages/categorias-nps/categoria-nps-form').then((m) => m.CategoriaNpsForm),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova categoria de NPS',
      },
      {
        path: 'categorias-nps/:id',
        loadComponent: () => import('./pages/categorias-nps/categoria-nps-form').then((m) => m.CategoriaNpsForm),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar categoria de NPS',
      },
      {
        path: 'pacientes',
        loadComponent: () => import('./pages/pacientes/pacientes-list').then((m) => m.PacientesList),
        canActivate: [telaGuard('PACIENTES')],
        title: 'Pacientes',
      },
      {
        path: 'pacientes/novo',
        loadComponent: () => import('./pages/pacientes/paciente-form').then((m) => m.PacienteForm),
        canActivate: [telaGuard('PACIENTES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo paciente',
      },
      {
        path: 'pacientes/:id',
        loadComponent: () => import('./pages/pacientes/paciente-form').then((m) => m.PacienteForm),
        canActivate: [telaGuard('PACIENTES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar paciente',
      },
      {
        path: 'especialidades',
        loadComponent: () => import('./pages/especialidades/especialidades-list').then((m) => m.EspecialidadesList),
        canActivate: [telaGuard('ESPECIALIDADES')],
        title: 'Especialidades',
      },
      {
        path: 'especialidades/novo',
        loadComponent: () => import('./pages/especialidades/especialidade-form').then((m) => m.EspecialidadeForm),
        canActivate: [telaGuard('ESPECIALIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova especialidade',
      },
      {
        path: 'especialidades/:id',
        loadComponent: () => import('./pages/especialidades/especialidade-form').then((m) => m.EspecialidadeForm),
        canActivate: [telaGuard('ESPECIALIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar especialidade',
      },
      {
        path: 'motivos-falta',
        loadComponent: () => import('./pages/motivos-falta/motivos-falta-list').then((m) => m.MotivosFaltaList),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        title: 'Motivos de falta',
      },
      {
        path: 'motivos-falta/novo',
        loadComponent: () => import('./pages/motivos-falta/motivo-falta-form').then((m) => m.MotivoFaltaForm),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo motivo de falta',
      },
      {
        path: 'motivos-falta/:id',
        loadComponent: () => import('./pages/motivos-falta/motivo-falta-form').then((m) => m.MotivoFaltaForm),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar motivo de falta',
      },
      {
        path: 'profissionais',
        loadComponent: () => import('./pages/profissionais/profissionais-list').then((m) => m.ProfissionalSaudesList),
        canActivate: [telaGuard('PROFISSIONAIS')],
        title: 'Profissionais',
      },
      {
        path: 'profissionais/novo',
        loadComponent: () => import('./pages/profissionais/profissional-form').then((m) => m.ProfissionalSaudeForm),
        canActivate: [telaGuard('PROFISSIONAIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo profissional',
      },
      {
        path: 'profissionais/:id',
        loadComponent: () => import('./pages/profissionais/profissional-form').then((m) => m.ProfissionalSaudeForm),
        canActivate: [telaGuard('PROFISSIONAIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar profissional',
      },
      {
        path: 'conselhos',
        loadComponent: () => import('./pages/conselhos/conselhos-list').then((m) => m.ConselhosList),
        canActivate: [telaGuard('CONSELHOS')],
        title: 'Conselhos',
      },
      {
        path: 'conselhos/novo',
        loadComponent: () => import('./pages/conselhos/conselho-form').then((m) => m.ConselhoForm),
        canActivate: [telaGuard('CONSELHOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo conselho',
      },
      {
        path: 'conselhos/:id',
        loadComponent: () => import('./pages/conselhos/conselho-form').then((m) => m.ConselhoForm),
        canActivate: [telaGuard('CONSELHOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar conselho',
      },
      {
        path: 'procedimentos',
        loadComponent: () => import('./pages/procedimentos/procedimentos-list').then((m) => m.ProcedimentosList),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        title: 'Procedimentos',
      },
      {
        path: 'procedimentos/novo',
        loadComponent: () => import('./pages/procedimentos/procedimento-form').then((m) => m.ProcedimentoForm),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo procedimento',
      },
      {
        path: 'procedimentos/:id',
        loadComponent: () => import('./pages/procedimentos/procedimento-form').then((m) => m.ProcedimentoForm),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar procedimento',
      },
      {
        path: 'prontuarios',
        loadComponent: () => import('./pages/prontuarios/prontuarios-list').then((m) => m.ProntuariosList),
        canActivate: [telaGuard('PRONTUARIOS')],
        title: 'Prontuários',
      },
      {
        path: 'prontuarios/novo',
        loadComponent: () => import('./pages/prontuarios/prontuario-form').then((m) => m.ProntuarioForm),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo prontuário',
      },
      {
        path: 'prontuarios/:id',
        loadComponent: () => import('./pages/prontuarios/prontuario-form').then((m) => m.ProntuarioForm),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar prontuário',
      },
      {
        path: 'tipos-documento-prontuario',
        loadComponent: () =>
          import('./pages/tipos-documento-prontuario/tipos-documento-prontuario-list').then(
            (m) => m.TiposDocumentoProntuarioList,
          ),
        canActivate: [telaGuard('PRONTUARIOS')],
        title: 'Tipos de Documento',
      },
      {
        path: 'tipos-documento-prontuario/novo',
        loadComponent: () =>
          import('./pages/tipos-documento-prontuario/tipo-documento-prontuario-form').then(
            (m) => m.TipoDocumentoProntuarioForm,
          ),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo tipo de documento',
      },
      {
        path: 'tipos-documento-prontuario/:id',
        loadComponent: () =>
          import('./pages/tipos-documento-prontuario/tipo-documento-prontuario-form').then(
            (m) => m.TipoDocumentoProntuarioForm,
          ),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar tipo de documento',
      },
      {
        path: 'prontuario-medico',
        loadComponent: () =>
          import('./pages/prontuario-medico/prontuario-medico-busca').then((m) => m.ProntuarioMedicoBusca),
        canActivate: [telaGuard('PRONTUARIO_MEDICO')],
        title: 'Prontuário Médico',
      },
      {
        path: 'prontuario-medico/:pacienteId',
        loadComponent: () =>
          import('./pages/prontuario-medico/prontuario-medico-historico').then((m) => m.ProntuarioMedicoHistorico),
        canActivate: [telaGuard('PRONTUARIO_MEDICO')],
        title: 'Prontuário Médico',
      },
      {
        path: 'postagens',
        loadComponent: () => import('./pages/postagens/postagens-list').then((m) => m.PostagensList),
        canActivate: [telaGuard('POSTAGENS')],
        title: 'Rede Social',
      },
      {
        path: 'postagens/novo',
        loadComponent: () => import('./pages/postagens/postagem-form').then((m) => m.PostagemForm),
        canActivate: [telaGuard('POSTAGENS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova postagem',
      },
      {
        path: 'postagens/rede-social',
        loadComponent: () => import('./pages/postagens/rede-social').then((m) => m.RedeSocial),
        canActivate: [telaGuard('POSTAGENS')],
        title: 'Rede Social',
      },
      {
        path: 'postagens/:id',
        loadComponent: () => import('./pages/postagens/postagem-form').then((m) => m.PostagemForm),
        canActivate: [telaGuard('POSTAGENS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar postagem',
      },
      {
        path: 'perfis',
        loadComponent: () => import('./pages/perfis/perfis-list').then((m) => m.PerfisList),
        canActivate: [telaGuard('PERFIS')],
        title: 'Perfis de acesso',
      },
      {
        path: 'perfis/novo',
        loadComponent: () => import('./pages/perfis/perfil-form').then((m) => m.PerfilForm),
        canActivate: [telaGuard('PERFIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo perfil',
      },
      {
        path: 'perfis/:id',
        loadComponent: () => import('./pages/perfis/perfil-form').then((m) => m.PerfilForm),
        canActivate: [telaGuard('PERFIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar perfil',
      },
      {
        path: 'configuracoes',
        loadComponent: () =>
          import('./pages/configuracoes/configuracoes-list').then((m) => m.ConfiguracoesList),
        canActivate: [telaGuard('CONFIGURACOES')],
        title: 'Configurações',
      },
      {
        path: 'configuracoes/:id',
        loadComponent: () =>
          import('./pages/configuracoes/configuracao-form').then((m) => m.ConfiguracaoForm),
        canActivate: [telaGuard('CONFIGURACOES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar configuração',
      },
      {
        path: 'uso-ia',
        loadComponent: () => import('./pages/uso-ia/uso-ia-list').then((m) => m.UsoIaList),
        canActivate: [telaGuard('USO_IA')],
        title: 'Uso de IA',
      },
      { path: '', redirectTo: 'inicio', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: 'login' },
];
