import { Routes } from '@angular/router';
import { authGuard, inicioGuard, selecionarUnidadeGuard, telaGuard } from './core/auth.guard';
import { pendingChangesGuard } from './core/pending-changes.guard';

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./pages/login/login').then((m) => m.Login),
    title: 'Entrar — Portal do Paciente · Admin',
  },
  {
    path: 'selecionar-unidade',
    loadComponent: () =>
      import('./pages/selecionar-unidade/selecionar-unidade').then((m) => m.SelecionarUnidade),
    canActivate: [selecionarUnidadeGuard],
    title: 'Selecione a unidade — Portal do Paciente · Admin',
  },
  {
    path: '',
    loadComponent: () => import('./pages/shell/shell').then((m) => m.Shell),
    canActivate: [authGuard],
    children: [
      {
        path: 'dashboards/geral',
        loadComponent: () => import('./pages/dashboards/geral/geral').then((m) => m.DashboardGeral),
        canActivate: [telaGuard('DASHBOARD')],
        title: 'Dashboard · Visão geral — Portal do Paciente · Admin',
      },
      {
        path: 'dashboards/agendamentos',
        loadComponent: () =>
          import('./pages/dashboards/agendamentos/agendamentos').then((m) => m.DashboardAgendamentos),
        canActivate: [telaGuard('DASHBOARD')],
        title: 'Dashboard · Agendamentos — Portal do Paciente · Admin',
      },
      {
        path: 'dashboards/chats',
        loadComponent: () => import('./pages/dashboards/chats/chats').then((m) => m.DashboardChats),
        canActivate: [telaGuard('DASHBOARD')],
        title: 'Dashboard · Chats ao vivo — Portal do Paciente · Admin',
      },
      {
        path: 'dashboards/sau',
        loadComponent: () => import('./pages/dashboards/sau/sau').then((m) => m.DashboardSau),
        canActivate: [telaGuard('DASHBOARD')],
        title: 'Dashboard · SAU — Portal do Paciente · Admin',
      },
      {
        path: 'dashboards/nps',
        loadComponent: () => import('./pages/dashboards/nps/nps').then((m) => m.DashboardNps),
        canActivate: [telaGuard('DASHBOARD')],
        title: 'Dashboard · NPS — Portal do Paciente · Admin',
      },
      { path: 'inicio', canActivate: [inicioGuard], children: [] },
      {
        path: 'sem-permissao',
        loadComponent: () => import('./pages/sem-permissao/sem-permissao').then((m) => m.SemPermissao),
        title: 'Sem permissão — Portal do Paciente · Admin',
      },
      {
        path: 'usuarios',
        loadComponent: () => import('./pages/usuarios/usuarios-list').then((m) => m.UsuariosList),
        canActivate: [telaGuard('USUARIOS')],
        title: 'Usuários — Portal do Paciente · Admin',
      },
      {
        path: 'usuarios/novo',
        loadComponent: () => import('./pages/usuarios/usuario-form').then((m) => m.UsuarioForm),
        canActivate: [telaGuard('USUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo usuário — Portal do Paciente · Admin',
      },
      {
        path: 'usuarios/:id',
        loadComponent: () => import('./pages/usuarios/usuario-form').then((m) => m.UsuarioForm),
        canActivate: [telaGuard('USUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar usuário — Portal do Paciente · Admin',
      },
      {
        path: 'unidades',
        loadComponent: () => import('./pages/unidades/unidades-list').then((m) => m.UnidadesList),
        canActivate: [telaGuard('UNIDADES')],
        title: 'Unidades de Saúde — Portal do Paciente · Admin',
      },
      {
        path: 'unidades/novo',
        loadComponent: () => import('./pages/unidades/unidade-form').then((m) => m.UnidadeForm),
        canActivate: [telaGuard('UNIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova unidade — Portal do Paciente · Admin',
      },
      {
        path: 'unidades/:id',
        loadComponent: () => import('./pages/unidades/unidade-form').then((m) => m.UnidadeForm),
        canActivate: [telaGuard('UNIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar unidade — Portal do Paciente · Admin',
      },
      {
        path: 'agendamentos',
        loadComponent: () => import('./pages/agendamentos/agendamentos-list').then((m) => m.AgendamentosList),
        canActivate: [telaGuard('AGENDAMENTOS')],
        title: 'Agendamentos — Portal do Paciente · Admin',
      },
      {
        path: 'agendamentos/novo',
        loadComponent: () => import('./pages/agendamentos/agendamento-form').then((m) => m.AgendamentoForm),
        canActivate: [telaGuard('AGENDAMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo agendamento — Portal do Paciente · Admin',
      },
      {
        path: 'agendamentos/:id',
        loadComponent: () => import('./pages/agendamentos/agendamento-form').then((m) => m.AgendamentoForm),
        canActivate: [telaGuard('AGENDAMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar agendamento — Portal do Paciente · Admin',
      },
      {
        path: 'chats',
        loadComponent: () => import('./pages/chats/chats-list').then((m) => m.ChatsList),
        canActivate: [telaGuard('CHATS')],
        title: 'Chats ao vivo — Portal do Paciente · Admin',
      },
      {
        path: 'chats/nova',
        loadComponent: () => import('./pages/chats/chat-nova').then((m) => m.ChatNova),
        canActivate: [telaGuard('CHATS')],
        title: 'Nova conversa — Portal do Paciente · Admin',
      },
      {
        path: 'chats/:id',
        loadComponent: () => import('./pages/chats/chat-conversa').then((m) => m.ChatConversa),
        canActivate: [telaGuard('CHATS')],
        title: 'Conversa — Portal do Paciente · Admin',
      },
      {
        path: 'sau',
        loadComponent: () => import('./pages/sau/sau-list').then((m) => m.SauList),
        canActivate: [telaGuard('SAU')],
        title: 'SAU — Portal do Paciente · Admin',
      },
      {
        path: 'sau/:id',
        loadComponent: () => import('./pages/sau/sau-detalhe').then((m) => m.SauDetalhe),
        canActivate: [telaGuard('SAU')],
        title: 'Manifestação — Portal do Paciente · Admin',
      },
      {
        path: 'tipos-manifestacao',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipos-manifestacao-list').then((m) => m.TiposManifestacaoList),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        title: 'Tipos de Manifestação — Portal do Paciente · Admin',
      },
      {
        path: 'tipos-manifestacao/novo',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipo-manifestacao-form').then((m) => m.TipoManifestacaoForm),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo tipo de manifestação — Portal do Paciente · Admin',
      },
      {
        path: 'tipos-manifestacao/:id',
        loadComponent: () =>
          import('./pages/tipos-manifestacao/tipo-manifestacao-form').then((m) => m.TipoManifestacaoForm),
        canActivate: [telaGuard('TIPOS_MANIFESTACAO')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar tipo de manifestação — Portal do Paciente · Admin',
      },
      {
        path: 'nps',
        loadComponent: () => import('./pages/nps/nps-list').then((m) => m.NpsList),
        canActivate: [telaGuard('NPS')],
        title: 'NPS — Portal do Paciente · Admin',
      },
      {
        path: 'nps/:id',
        loadComponent: () => import('./pages/nps/nps-detalhe').then((m) => m.NpsDetalheComponent),
        canActivate: [telaGuard('NPS')],
        title: 'Avaliação — Portal do Paciente · Admin',
      },
      {
        path: 'categorias-nps',
        loadComponent: () => import('./pages/categorias-nps/categorias-nps-list').then((m) => m.CategoriasNpsList),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        title: 'Categorias de NPS — Portal do Paciente · Admin',
      },
      {
        path: 'categorias-nps/novo',
        loadComponent: () => import('./pages/categorias-nps/categoria-nps-form').then((m) => m.CategoriaNpsForm),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova categoria de NPS — Portal do Paciente · Admin',
      },
      {
        path: 'categorias-nps/:id',
        loadComponent: () => import('./pages/categorias-nps/categoria-nps-form').then((m) => m.CategoriaNpsForm),
        canActivate: [telaGuard('CATEGORIAS_NPS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar categoria de NPS — Portal do Paciente · Admin',
      },
      {
        path: 'pacientes',
        loadComponent: () => import('./pages/pacientes/pacientes-list').then((m) => m.PacientesList),
        canActivate: [telaGuard('PACIENTES')],
        title: 'Pacientes — Portal do Paciente · Admin',
      },
      {
        path: 'pacientes/novo',
        loadComponent: () => import('./pages/pacientes/paciente-form').then((m) => m.PacienteForm),
        canActivate: [telaGuard('PACIENTES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo paciente — Portal do Paciente · Admin',
      },
      {
        path: 'pacientes/:id',
        loadComponent: () => import('./pages/pacientes/paciente-form').then((m) => m.PacienteForm),
        canActivate: [telaGuard('PACIENTES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar paciente — Portal do Paciente · Admin',
      },
      {
        path: 'especialidades',
        loadComponent: () => import('./pages/especialidades/especialidades-list').then((m) => m.EspecialidadesList),
        canActivate: [telaGuard('ESPECIALIDADES')],
        title: 'Especialidades — Portal do Paciente · Admin',
      },
      {
        path: 'especialidades/novo',
        loadComponent: () => import('./pages/especialidades/especialidade-form').then((m) => m.EspecialidadeForm),
        canActivate: [telaGuard('ESPECIALIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova especialidade — Portal do Paciente · Admin',
      },
      {
        path: 'especialidades/:id',
        loadComponent: () => import('./pages/especialidades/especialidade-form').then((m) => m.EspecialidadeForm),
        canActivate: [telaGuard('ESPECIALIDADES')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar especialidade — Portal do Paciente · Admin',
      },
      {
        path: 'motivos-falta',
        loadComponent: () => import('./pages/motivos-falta/motivos-falta-list').then((m) => m.MotivosFaltaList),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        title: 'Motivos de falta — Portal do Paciente · Admin',
      },
      {
        path: 'motivos-falta/novo',
        loadComponent: () => import('./pages/motivos-falta/motivo-falta-form').then((m) => m.MotivoFaltaForm),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo motivo de falta — Portal do Paciente · Admin',
      },
      {
        path: 'motivos-falta/:id',
        loadComponent: () => import('./pages/motivos-falta/motivo-falta-form').then((m) => m.MotivoFaltaForm),
        canActivate: [telaGuard('MOTIVOS_FALTA')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar motivo de falta — Portal do Paciente · Admin',
      },
      {
        path: 'profissionais',
        loadComponent: () => import('./pages/profissionais/profissionais-list').then((m) => m.ProfissionalSaudesList),
        canActivate: [telaGuard('PROFISSIONAIS')],
        title: 'Profissionais — Portal do Paciente · Admin',
      },
      {
        path: 'profissionais/novo',
        loadComponent: () => import('./pages/profissionais/profissional-form').then((m) => m.ProfissionalSaudeForm),
        canActivate: [telaGuard('PROFISSIONAIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo profissional — Portal do Paciente · Admin',
      },
      {
        path: 'profissionais/:id',
        loadComponent: () => import('./pages/profissionais/profissional-form').then((m) => m.ProfissionalSaudeForm),
        canActivate: [telaGuard('PROFISSIONAIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar profissional — Portal do Paciente · Admin',
      },
      {
        path: 'procedimentos',
        loadComponent: () => import('./pages/procedimentos/procedimentos-list').then((m) => m.ProcedimentosList),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        title: 'Procedimentos — Portal do Paciente · Admin',
      },
      {
        path: 'procedimentos/novo',
        loadComponent: () => import('./pages/procedimentos/procedimento-form').then((m) => m.ProcedimentoForm),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo procedimento — Portal do Paciente · Admin',
      },
      {
        path: 'procedimentos/:id',
        loadComponent: () => import('./pages/procedimentos/procedimento-form').then((m) => m.ProcedimentoForm),
        canActivate: [telaGuard('PROCEDIMENTOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar procedimento — Portal do Paciente · Admin',
      },
      {
        path: 'prontuarios',
        loadComponent: () => import('./pages/prontuarios/prontuarios-list').then((m) => m.ProntuariosList),
        canActivate: [telaGuard('PRONTUARIOS')],
        title: 'Prontuários — Portal do Paciente · Admin',
      },
      {
        path: 'prontuarios/novo',
        loadComponent: () => import('./pages/prontuarios/prontuario-form').then((m) => m.ProntuarioForm),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo prontuário — Portal do Paciente · Admin',
      },
      {
        path: 'prontuarios/:id',
        loadComponent: () => import('./pages/prontuarios/prontuario-form').then((m) => m.ProntuarioForm),
        canActivate: [telaGuard('PRONTUARIOS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar prontuário — Portal do Paciente · Admin',
      },
      {
        path: 'postagens',
        loadComponent: () => import('./pages/postagens/postagens-list').then((m) => m.PostagensList),
        canActivate: [telaGuard('POSTAGENS')],
        title: 'Rede Social — Portal do Paciente · Admin',
      },
      {
        path: 'postagens/novo',
        loadComponent: () => import('./pages/postagens/postagem-form').then((m) => m.PostagemForm),
        canActivate: [telaGuard('POSTAGENS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Nova postagem — Portal do Paciente · Admin',
      },
      {
        path: 'postagens/rede-social',
        loadComponent: () => import('./pages/postagens/rede-social').then((m) => m.RedeSocial),
        canActivate: [telaGuard('POSTAGENS')],
        title: 'Rede Social — Portal do Paciente · Admin',
      },
      {
        path: 'postagens/:id',
        loadComponent: () => import('./pages/postagens/postagem-form').then((m) => m.PostagemForm),
        canActivate: [telaGuard('POSTAGENS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar postagem — Portal do Paciente · Admin',
      },
      {
        path: 'perfis',
        loadComponent: () => import('./pages/perfis/perfis-list').then((m) => m.PerfisList),
        canActivate: [telaGuard('PERFIS')],
        title: 'Perfis de acesso — Portal do Paciente · Admin',
      },
      {
        path: 'perfis/novo',
        loadComponent: () => import('./pages/perfis/perfil-form').then((m) => m.PerfilForm),
        canActivate: [telaGuard('PERFIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Novo perfil — Portal do Paciente · Admin',
      },
      {
        path: 'perfis/:id',
        loadComponent: () => import('./pages/perfis/perfil-form').then((m) => m.PerfilForm),
        canActivate: [telaGuard('PERFIS')],
        canDeactivate: [pendingChangesGuard],
        title: 'Editar perfil — Portal do Paciente · Admin',
      },
      {
        path: 'configuracoes',
        canActivate: [telaGuard('CONFIGURACOES')],
        ...secao('Configurações', 'Ajuste as preferências do sistema.'),
      },
      { path: '', redirectTo: 'inicio', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: 'login' },
];

function secao(title: string, description: string) {
  return {
    loadComponent: () => import('./pages/placeholder/placeholder').then((m) => m.Placeholder),
    title: `${title} — Portal do Paciente · Admin`,
    data: { title, description },
  };
}
